# Generates a Kex spec file from the Ruby calendar reference.
#
#   ruby tools/calendar_ref/gen_spec.rb > spec/prelude/time_generated.spec.kex
#
# Every assertion's expected value comes from Ruby's built-in calendar, so the
# generated file is a differential test: it passes only where Kex's
# src/stdlib/time.kex agrees with Ruby.
#
# The output is checked in. Regenerate it when the calendar API changes, and
# read the diff — a changed expectation means Ruby's answer moved, which
# should essentially never happen, so it is a signal that the generator (not
# Kex) needs a second look.
#
# Options:
#   --seed N     RNG seed (default 20260802); the seed is written into the
#                generated file so any run is reproducible.
#   --cases N    Random cases per fuzz section (default 40).

require_relative "calendar_ref"

SEED = (ARGV[ARGV.index("--seed") + 1].to_i if ARGV.include?("--seed")) || 20_260_802
CASES = (ARGV[ARGV.index("--cases") + 1].to_i if ARGV.include?("--cases")) || 40

RNG = Random.new(SEED)

# Years Kex renders with the plain four-digit ISO spelling. Deliberately
# straddles the epoch so pre-1970 arithmetic (where truncating division needs
# a floor correction) is exercised on every run.
YEAR_RANGE = (1583..2400).freeze

# ── Emitting ──────────────────────────────────────────────────────────────

$out = []

def line(text = "")
  $out << text
end

def describe(name)
  line("describe(#{name.inspect}) do")
  yield
  line("end")
  line
end

def it(name)
  line("  it(#{name.inspect}) do")
  yield
  line("  end")
  line
end

# One differential assertion. `expr` is Kex source; `expected` is the Ruby
# answer, rendered as a Kex literal.
def assert_eq(expr, expected)
  literal = expected.is_a?(String) ? expected.inspect : expected.to_s
  line("    assert(#{expr} == #{literal}, \"#{expr.gsub('"', '\\"')}\")")
end

def assert_true(expr)
  line("    assert(#{expr}, \"#{expr.gsub('"', '\\"')}\")")
end

# ── Case generators ───────────────────────────────────────────────────────

def random_date
  year = RNG.rand(YEAR_RANGE)
  month = RNG.rand(1..12)
  [year, month, RNG.rand(1..CalendarRef.days_in_month(year, month))]
end

def random_time
  [RNG.rand(0..23), RNG.rand(0..59), RNG.rand(0..59)]
end

# Whole-minute offsets, the only kind ISO 8601 can spell.
def random_offset
  [0, 0, 0, 1800, 2700].sample(random: RNG) + RNG.rand(-12..14) * 3600
end

def kex_date(year, month, day)
  "Date.of(#{year}, #{month}, #{day}).try"
end

def kex_duration(seconds)
  return "Duration.zero()" if seconds.zero?

  "Duration.seconds(#{seconds})"
end

# ── The spec ──────────────────────────────────────────────────────────────

line "# GENERATED by tools/calendar_ref/gen_spec.rb — do not edit by hand."
line "#"
line "# Every expected value below is Ruby's answer, taken from its built-in"
line "# Date/Time classes via tools/calendar_ref/calendar_ref.rb. Regenerate with:"
line "#"
line "#   ruby tools/calendar_ref/gen_spec.rb > spec/prelude/time_generated.spec.kex"
line "#"
line "# seed: #{SEED}, cases per section: #{CASES}"
line

describe "Time.leapYear? (vs Ruby)" do
  it "agrees on century and ordinary years" do
    [1600, 1700, 1800, 1900, 2000, 2024, 2025, 2026, 2028, 2100, 2400].each do |year|
      assert_eq("Time.leapYear?(#{year})", CalendarRef.leap_year?(year))
    end
  end

  it "agrees on random years" do
    CASES.times do
      year = RNG.rand(YEAR_RANGE)
      assert_eq("Time.leapYear?(#{year})", CalendarRef.leap_year?(year))
    end
  end
end

describe "Time.daysInMonth (vs Ruby)" do
  it "agrees on every month of a leap and a common year" do
    [2026, 2028].each do |year|
      (1..12).each do |month|
        assert_eq("Time.daysInMonth(#{year}, #{month}).try",
                  CalendarRef.days_in_month(year, month))
      end
    end
  end

  it "has no answer for a month outside 1..12" do
    # The trap this replaced: month-first arguments used to fall through to a
    # plausible-looking 28.
    [[1, 2026], [2026, 0], [2026, 13], [2026, -1], [0, 0]].each do |year, month|
      assert_eq("Time.daysInMonth(#{year}, #{month}).ok?", (1..12).cover?(month))
    end
  end

  it "agrees on random year/month pairs" do
    CASES.times do
      year = RNG.rand(YEAR_RANGE)
      month = RNG.rand(1..12)
      assert_eq("Time.daysInMonth(#{year}, #{month}).try",
                CalendarRef.days_in_month(year, month))
    end
  end
end

describe "epoch days (vs Ruby)" do
  it "agrees on fixed landmarks" do
    [[1970, 1, 1], [1969, 12, 31], [2000, 3, 1], [1900, 1, 1], [2026, 8, 2]].each do |date|
      assert_eq("#{kex_date(*date)}.epochDay", CalendarRef.days_from_civil(*date))
    end
  end

  it "round-trips random dates through epoch days" do
    CASES.times do
      date = random_date
      epoch_day = CalendarRef.days_from_civil(*date)
      assert_eq("#{kex_date(*date)}.epochDay", epoch_day)
      assert_eq("Date.fromEpochDay(#{epoch_day}).iso", CalendarRef.format_date(*date))
    end
  end

  it "round-trips random epoch days through civil dates" do
    CASES.times do
      # Roughly 1700..2300 in epoch days.
      epoch_day = RNG.rand(-98_000..120_000)
      assert_eq("Date.fromEpochDay(#{epoch_day}).iso",
                CalendarRef.format_date(*CalendarRef.civil_from_days(epoch_day)))
    end
  end
end

describe "weekdays (vs Ruby)" do
  it "agrees on random dates" do
    CASES.times do
      date = random_date
      epoch_day = CalendarRef.days_from_civil(*date)
      assert_eq("#{kex_date(*date)}.weekday.name",
                CalendarRef.weekday_name_from_epoch_day(epoch_day))
      assert_eq("#{kex_date(*date)}.weekday.number",
                CalendarRef.weekday_number_from_epoch_day(epoch_day))
      assert_eq("#{kex_date(*date)}.weekday.weekend?",
                CalendarRef.weekend_from_epoch_day?(epoch_day))
    end
  end
end

describe "day of year (vs Ruby)" do
  it "agrees on random dates" do
    CASES.times do
      date = random_date
      assert_eq("#{kex_date(*date)}.dayOfYear", CalendarRef.day_of_year(*date))
    end
  end
end

describe "date arithmetic (vs Ruby)" do
  it "adds and subtracts days" do
    CASES.times do
      date = random_date
      count = RNG.rand(-4000..4000)
      assert_eq("#{kex_date(*date)}.addDays(#{count}).iso",
                CalendarRef.format_date(*CalendarRef.add_days(*date, count)))
    end
  end

  it "adds weeks" do
    CASES.times do
      date = random_date
      count = RNG.rand(-500..500)
      assert_eq("#{kex_date(*date)}.addWeeks(#{count}).iso",
                CalendarRef.format_date(*CalendarRef.add_days(*date, count * 7)))
    end
  end

  it "adds months, clamping into short months" do
    # The clamping cases are the ones that break naive implementations, so
    # they are pinned explicitly as well as fuzzed.
    [[[2026, 1, 31], 1], [[2026, 1, 31], 13], [[2026, 1, 31], -1],
     [[2026, 1, 31], -13], [[2028, 2, 29], 12], [[2026, 3, 31], -1],
     [[2026, 5, 31], -3], [[2026, 12, 31], 2]].each do |date, count|
      assert_eq("#{kex_date(*date)}.addMonths(#{count}).iso",
                CalendarRef.format_date(*CalendarRef.add_months(*date, count)))
    end
    CASES.times do
      date = random_date
      count = RNG.rand(-400..400)
      assert_eq("#{kex_date(*date)}.addMonths(#{count}).iso",
                CalendarRef.format_date(*CalendarRef.add_months(*date, count)))
    end
  end

  it "adds years" do
    CASES.times do
      date = random_date
      count = RNG.rand(-200..200)
      assert_eq("#{kex_date(*date)}.addYears(#{count}).iso",
                CalendarRef.format_date(*CalendarRef.add_years(*date, count)))
    end
  end

  it "steps to yesterday and tomorrow" do
    CASES.times do
      date = random_date
      assert_eq("#{kex_date(*date)}.tomorrow.iso",
                CalendarRef.format_date(*CalendarRef.add_days(*date, 1)))
      assert_eq("#{kex_date(*date)}.yesterday.iso",
                CalendarRef.format_date(*CalendarRef.add_days(*date, -1)))
    end
  end

  it "measures the distance between dates" do
    CASES.times do
      from = random_date
      to = random_date
      assert_eq("#{kex_date(*from)}.daysUntil(#{kex_date(*to)})",
                CalendarRef.days_until(from, to))
    end
  end

  it "orders dates" do
    CASES.times do
      from = random_date
      to = random_date
      gap = CalendarRef.days_until(from, to)
      assert_eq("#{kex_date(*from)}.before?(#{kex_date(*to)})", gap.positive?)
      assert_eq("#{kex_date(*from)}.after?(#{kex_date(*to)})", gap.negative?)
    end
  end
end

describe "date operators (vs Ruby)" do
  it "shifts a date by a whole-day Duration" do
    CASES.times do
      date = random_date
      count = RNG.rand(-2000..2000)
      shifted = CalendarRef.format_date(*CalendarRef.add_days(*date, count))
      # Parenthesised: `-5.days` parses as unary minus applied to a Duration,
      # which has no operator. `(-5).days` builds the negative span directly.
      assert_eq("(#{kex_date(*date)} + (#{count}).days).iso", shifted)
      assert_eq("(#{kex_date(*date)} - (#{-count}).days).iso", shifted)
    end
  end
end

describe "date validation (vs Ruby)" do
  it "rejects exactly the field combinations Ruby rejects" do
    cases = [[2026, 2, 29], [2028, 2, 29], [2026, 2, 30], [2026, 13, 1],
             [2026, 0, 1], [2026, 4, 31], [2026, 4, 30], [2026, 1, 0],
             [1900, 2, 29], [2000, 2, 29]]
    CASES.times { cases << [RNG.rand(YEAR_RANGE), RNG.rand(0..13), RNG.rand(0..32)] }
    cases.each do |year, month, day|
      assert_eq("Date.of(#{year}, #{month}, #{day}).ok?",
                CalendarRef.valid_date?(year, month, day))
    end
  end
end

describe "time of day (vs Ruby)" do
  it "validates fields" do
    cases = [[0, 0, 0], [23, 59, 59], [24, 0, 0], [0, 60, 0], [0, 0, 60], [-1, 0, 0]]
    CASES.times { cases << [RNG.rand(-1..24), RNG.rand(-1..60), RNG.rand(-1..60)] }
    cases.each do |hour, minute, second|
      assert_eq("Time.of(#{hour}, #{minute}, #{second}).ok?",
                CalendarRef.valid_time?(hour, minute, second))
    end
  end

  it "round-trips seconds since midnight" do
    CASES.times do
      time = random_time
      total = CalendarRef.seconds_since_midnight(*time)
      assert_eq("Time.of(#{time.join(', ')}).try.secondsSinceMidnight", total)
      assert_eq("Time.fromSecondsSinceMidnight(#{total}).iso",
                CalendarRef.format_time(*time))
    end
  end

  it "wraps out-of-range seconds since midnight" do
    CASES.times do
      count = RNG.rand(-200_000..200_000)
      assert_eq("Time.fromSecondsSinceMidnight(#{count}).iso",
                CalendarRef.format_time(*CalendarRef.from_seconds_since_midnight(count)))
    end
  end

  it "parses ISO times" do
    CASES.times do
      time = random_time
      text = CalendarRef.format_time(*time)
      assert_eq("Time.parse(#{text.inspect}).try.iso", text)
    end
  end
end

describe "instants (vs Ruby)" do
  it "converts civil datetimes to epoch seconds" do
    CASES.times do
      date = random_date
      time = random_time
      offset = random_offset
      dt = "DateTime.of(#{kex_date(*date)}, Time.of(#{time.join(', ')}).try, " \
           "#{kex_duration(offset)})"
      assert_eq("#{dt}.epochSeconds", CalendarRef.epoch_seconds(date, time, offset))
    end
  end

  it "renders instants back into civil datetimes" do
    CASES.times do
      # Roughly 1700..2300.
      count = RNG.rand(-8_500_000_000..10_400_000_000)
      offset = random_offset
      date, time = CalendarRef.from_epoch_seconds(count, offset)
      assert_eq("DateTime.fromEpochSeconds(#{count}, #{kex_duration(offset)}).iso",
                CalendarRef.format_date_time(date, time, offset))
    end
  end

  it "round-trips ISO datetimes" do
    CASES.times do
      date = random_date
      time = random_time
      offset = random_offset
      text = CalendarRef.format_date_time(date, time, offset)
      assert_eq("DateTime.parse(#{text.inspect}).try.iso", text)
      assert_eq("DateTime.parse(#{text.inspect}).try.epochSeconds",
                CalendarRef.epoch_seconds(date, time, offset))
    end
  end

  it "re-renders the same instant at another offset" do
    CASES.times do
      date = random_date
      time = random_time
      from = random_offset
      to = random_offset
      instant = CalendarRef.epoch_seconds(date, time, from)
      shifted_date, shifted_time = CalendarRef.from_epoch_seconds(instant, to)
      dt = "DateTime.of(#{kex_date(*date)}, Time.of(#{time.join(', ')}).try, " \
           "#{kex_duration(from)})"
      assert_eq("#{dt}.at(#{kex_duration(to)}).iso",
                CalendarRef.format_date_time(shifted_date, shifted_time, to))
      # The offset is a rendering, not part of the identity.
      assert_eq("#{dt}.at(#{kex_duration(to)}).epochSeconds", instant)
    end
  end

  it "shifts instants by a Duration" do
    CASES.times do
      date = random_date
      time = random_time
      offset = random_offset
      span = RNG.rand(-40_000_000..40_000_000)
      instant = CalendarRef.epoch_seconds(date, time, offset)
      shifted_date, shifted_time = CalendarRef.from_epoch_seconds(instant + span, offset)
      dt = "DateTime.of(#{kex_date(*date)}, Time.of(#{time.join(', ')}).try, " \
           "#{kex_duration(offset)})"
      assert_eq("(#{dt} + #{kex_duration(span)}).iso",
                CalendarRef.format_date_time(shifted_date, shifted_time, offset))
      assert_eq("(#{dt} - #{kex_duration(-span)}).iso",
                CalendarRef.format_date_time(shifted_date, shifted_time, offset))
    end
  end
end

puts $out.join("\n")
