%% GENERATED by tools/unicode_gen.rb — do not edit by hand.
%%
%% Unicode simple (1:1) case mapping, for Char -> Char. OTP exposes no
%% such function: string:to_upper/1 is the pre-Unicode one and covers
%% only ISO-8859-1, while string:uppercase/1 is the FULL mapping and
%% may expand (ß -> SS). Taking the full mapping only when it stays one
%% codepoint recovers the simple mapping almost everywhere; the clauses
%% below are the codepoints where that is wrong, because they have BOTH
%% an expanding full mapping and a real simple one. Kept in step with
%% src/common/unicode_case.hxx, which is what the interpreter uses.
-module(kex_unicode_case).
-export([simple_upper/1, simple_lower/1]).

simple_upper(C) ->
    case string:uppercase([C]) of
        [Mapped] -> Mapped;
        _ -> upper_exception(C)
    end.

simple_lower(C) ->
    case string:lowercase([C]) of
        [Mapped] -> Mapped;
        _ -> lower_exception(C)
    end.

upper_exception(16#1F80) -> 16#1F88;
upper_exception(16#1F81) -> 16#1F89;
upper_exception(16#1F82) -> 16#1F8A;
upper_exception(16#1F83) -> 16#1F8B;
upper_exception(16#1F84) -> 16#1F8C;
upper_exception(16#1F85) -> 16#1F8D;
upper_exception(16#1F86) -> 16#1F8E;
upper_exception(16#1F87) -> 16#1F8F;
upper_exception(16#1F90) -> 16#1F98;
upper_exception(16#1F91) -> 16#1F99;
upper_exception(16#1F92) -> 16#1F9A;
upper_exception(16#1F93) -> 16#1F9B;
upper_exception(16#1F94) -> 16#1F9C;
upper_exception(16#1F95) -> 16#1F9D;
upper_exception(16#1F96) -> 16#1F9E;
upper_exception(16#1F97) -> 16#1F9F;
upper_exception(16#1FA0) -> 16#1FA8;
upper_exception(16#1FA1) -> 16#1FA9;
upper_exception(16#1FA2) -> 16#1FAA;
upper_exception(16#1FA3) -> 16#1FAB;
upper_exception(16#1FA4) -> 16#1FAC;
upper_exception(16#1FA5) -> 16#1FAD;
upper_exception(16#1FA6) -> 16#1FAE;
upper_exception(16#1FA7) -> 16#1FAF;
upper_exception(16#1FB3) -> 16#1FBC;
upper_exception(16#1FC3) -> 16#1FCC;
upper_exception(16#1FF3) -> 16#1FFC;
upper_exception(C) -> C.

lower_exception(16#0130) -> 16#0069;
lower_exception(C) -> C.

