#!/usr/bin/env ruby
# frozen_string_literal: true
#
# Regenerates the Unicode tables both backends read. Ruby's own Unicode
# database is the only source — nothing is fetched and nothing is vendored.
#
#   ruby tools/unicode_gen.rb case-hxx     > src/common/unicode_case.hxx
#   ruby tools/unicode_gen.rb case-erl     > runtime/src/kex_unicode_case.erl
#   ruby tools/unicode_gen.rb category-hxx > src/common/unicode_category.hxx
#   ruby tools/unicode_gen.rb category-erl > runtime/src/kex_unicode_category.erl
#
# Two kinds of table, because the operations have different types:
#
#   Char.upperCase   : Char -> Char     needs the SIMPLE (1:1) mapping
#   String.upperCase : String -> String needs the FULL mapping, which may
#                                       expand ("straße" -> "STRASSE")
#
# Ruby exposes the full mapping directly (String#upcase / #downcase). It has
# no simple-mapping accessor, but the simple mapping is recoverable: it is the
# full mapping wherever that stays one codepoint, and for the ~100 codepoints
# that expand it is the TITLECASE where that is a single codepoint. U+1F80
# upcases to two codepoints yet has a real simple uppercase, U+1F88, which is
# exactly its titlecase; U+00DF upcases to "SS" and titlecases to "Ss", so it
# has no simple uppercase and stays ß. The one case that rule cannot reach is
# U+0130, handled explicitly below.
#
# Mappings are applied ONE CODEPOINT AT A TIME on purpose. That skips the
# context-sensitive rules (Greek final sigma), which is what BEAM's
# string:uppercase/1 does — the two backends have to agree.
#
# digit? is deliberately absent from the category tables: it stays ASCII
# '0'..'9'. It backs the stdlib's JSON number scanner, and JSON numbers are
# ASCII by specification, so accepting U+0665 ARABIC-INDIC DIGIT FIVE there
# would scan a number the conversion then could not parse.

MAX = 0x110000

# U+0130 LATIN CAPITAL LETTER I WITH DOT ABOVE downcases to "i" + combining
# dot above, two codepoints, while its simple lowercase is a plain "i". It is
# the only codepoint whose expanding full mapping hides a simple one that the
# titlecase does not recover.
DOTTED_CAPITAL_I = 0x0130

def surrogate?(cp)
  cp >= 0xD800 && cp <= 0xDFFF
end

def each_codepoint
  (0...MAX).each do |cp|
    next if surrogate?(cp)
    yield cp, cp.chr(Encoding::UTF_8)
  end
end

# full[cp] = [codepoints], only where the mapping differs from the source.
def full_maps
  upper = {}
  lower = {}
  each_codepoint do |cp, ch|
    up = ch.upcase
    down = ch.downcase
    upper[cp] = up.codepoints if up != ch
    lower[cp] = down.codepoints if down != ch
  end
  [upper, lower]
end

def simple_maps(full_upper, full_lower)
  upper = {}
  lower = {}
  full_upper.each do |cp, mapped|
    target =
      if mapped.length == 1
        mapped.first
      else
        title = cp.chr(Encoding::UTF_8).capitalize.codepoints
        title.length == 1 ? title.first : nil
      end
    upper[cp] = target if target && target != cp
  end
  full_lower.each do |cp, mapped|
    target =
      if mapped.length == 1
        mapped.first
      elsif cp == DOTTED_CAPITAL_I
        0x0069
      end
    lower[cp] = target if target && target != cp
  end
  [upper, lower]
end

# Compress to [start, end, stride, delta]. Case blocks are overwhelmingly
# either contiguous with a constant delta (ASCII, Cyrillic) or alternating
# upper/lower pairs (Latin Extended-A), so a stride of 1 or 2 collapses the
# table by roughly an order of magnitude.
def runs(mapping)
  items = mapping.sort
  out = []
  i = 0
  while i < items.length
    cp, target = items[i]
    delta = target - cp
    best = [cp, cp, 1, delta]
    [1, 2].each do |stride|
      last = cp
      j = i + 1
      while j < items.length && items[j][0] == last + stride &&
            items[j][1] - items[j][0] == delta
        last = items[j][0]
        j += 1
      end
      best = [cp, last, stride, delta] if last > best[1]
    end
    out << best
    i += (best[1] - best[0]) / best[2] + 1
  end
  out
end

# Collapse a sorted codepoint list into [start, end] runs.
def ranges(codepoints)
  out = []
  codepoints.each do |cp|
    if !out.empty? && cp == out.last[1] + 1
      out.last[1] = cp
    else
      out << [cp, cp]
    end
  end
  out
end

def categories
  letter = []
  upper = []
  lower = []
  space = []
  each_codepoint do |cp, ch|
    letter << cp if ch.match?(/\p{L}/)
    upper << cp if ch.match?(/\p{Lu}/)
    lower << cp if ch.match?(/\p{Ll}/)
    space << cp if ch.match?(/\p{Space}/)
  end
  { "letterRanges" => ranges(letter), "upperRanges" => ranges(upper),
    "lowerRanges" => ranges(lower), "spaceRanges" => ranges(space) }
end

def banner(comment)
  "#{comment} GENERATED by tools/unicode_gen.rb — do not edit by hand."
end

def emit_case_hxx
  full_upper, full_lower = full_maps
  simple_upper, simple_lower = simple_maps(full_upper, full_lower)
  expand_upper = full_upper.select { |_, m| m.length > 1 }
  expand_lower = full_lower.select { |_, m| m.length > 1 }

  puts "#pragma once"
  puts banner("//")
  puts "//"
  puts "// Unicode #{unicode_version} case mappings. `simple*` is the 1:1 mapping a"
  puts "// Char uses; `expand*` holds only the codepoints whose FULL mapping is"
  puts "// longer than one codepoint (ß -> SS), which a String uses on top of"
  puts "// the simple table. See the generator for how the two are derived."
  puts "#include <cstdint>"
  puts
  puts "namespace kex::utf8::tables {"
  puts
  puts "// [start, end] stepping by `stride`, each mapping to itself + delta."
  puts "struct CaseRun {"
  puts "    char32_t start;"
  puts "    char32_t end;"
  puts "    std::uint8_t stride;"
  puts "    std::int32_t delta;"
  puts "};"
  puts
  puts "// A full mapping that is longer than the source codepoint."
  puts "struct FullCase {"
  puts "    char32_t from;"
  puts "    std::uint8_t length;"
  puts "    char32_t to[3];"
  puts "};"
  puts
  { "simpleUpper" => simple_upper, "simpleLower" => simple_lower }.each do |name, map|
    puts "inline constexpr CaseRun #{name}[] = {"
    runs(map).each { |s, e, st, d| puts format("    {0x%04X, 0x%04X, %d, %d},", s, e, st, d) }
    puts "};"
    puts
  end
  { "expandUpper" => expand_upper, "expandLower" => expand_lower }.each do |name, map|
    puts "inline constexpr FullCase #{name}[] = {"
    map.sort.each do |cp, mapped|
      padded = mapped + [0] * (3 - mapped.length)
      puts format("    {0x%04X, %d, {0x%04X, 0x%04X, 0x%04X}},",
                  cp, mapped.length, *padded)
    end
    puts "};"
    puts
  end
  puts "} // namespace kex::utf8::tables"
end

def emit_case_erl
  full_upper, full_lower = full_maps
  simple_upper, simple_lower = simple_maps(full_upper, full_lower)
  expand_upper = full_upper.select { |_, m| m.length > 1 }
  expand_lower = full_lower.select { |_, m| m.length > 1 }

  puts banner("%%")
  puts "%%"
  puts "%% Unicode simple (1:1) case mapping, for Char -> Char. OTP exposes no"
  puts "%% such function: string:to_upper/1 is the pre-Unicode one and covers"
  puts "%% only ISO-8859-1, while string:uppercase/1 is the FULL mapping and"
  puts "%% may expand (ß -> SS). Taking the full mapping only when it stays one"
  puts "%% codepoint recovers the simple mapping almost everywhere; the clauses"
  puts "%% below are the codepoints where that is wrong, because they have BOTH"
  puts "%% an expanding full mapping and a real simple one. Kept in step with"
  puts "%% src/common/unicode_case.hxx, which is what the interpreter uses."
  puts "-module(kex_unicode_case)."
  puts "-export([simple_upper/1, simple_lower/1])."
  puts
  puts "simple_upper(C) ->"
  puts "    case string:uppercase([C]) of"
  puts "        [Mapped] -> Mapped;"
  puts "        _ -> upper_exception(C)"
  puts "    end."
  puts
  puts "simple_lower(C) ->"
  puts "    case string:lowercase([C]) of"
  puts "        [Mapped] -> Mapped;"
  puts "        _ -> lower_exception(C)"
  puts "    end."
  puts
  [["upper_exception", expand_upper, simple_upper],
   ["lower_exception", expand_lower, simple_lower]].each do |name, expanding, simple|
    expanding.keys.sort.each do |cp|
      next unless simple.key?(cp)
      puts format("%s(16#%04X) -> 16#%04X;", name, cp, simple[cp])
    end
    puts "#{name}(C) -> C."
    puts
  end
end

def emit_category_hxx
  tables = categories
  puts "#pragma once"
  puts banner("//")
  puts "//"
  puts "// Unicode #{unicode_version} character categories, as sorted codepoint"
  puts "// ranges. Backs Char.letter?/.alpha?/.upper?/.lower?/.space?. See the"
  puts "// generator for why digit? is not among them."
  puts "#include <cstddef>"
  puts
  puts "namespace kex::utf8::categories {"
  puts
  puts "struct Range {"
  puts "    char32_t start;"
  puts "    char32_t end;"
  puts "};"
  puts
  tables.each do |name, table|
    puts "inline constexpr Range #{name}[] = {"
    table.each { |s, e| puts format("    {0x%04X, 0x%04X},", s, e) }
    puts "};"
    puts
  end
  puts "template <std::size_t N>"
  puts "inline auto inRanges(const Range (&ranges)[N], char32_t c) -> bool {"
  puts "    std::size_t low = 0, high = N;"
  puts "    while (low < high) {"
  puts "        auto mid = low + (high - low) / 2;"
  puts "        if (c < ranges[mid].start) high = mid;"
  puts "        else if (c > ranges[mid].end) low = mid + 1;"
  puts "        else return true;"
  puts "    }"
  puts "    return false;"
  puts "}"
  puts
  puts "} // namespace kex::utf8::categories"
end

def emit_category_erl
  tables = categories
  puts banner("%%")
  puts "%%"
  puts "%% Unicode character categories as sorted codepoint ranges, binary"
  puts "%% searched. OTP exposes no category predicate, and the interpreter"
  puts "%% needs the identical answer, so both read from these tables."
  puts "-module(kex_unicode_category)."
  puts "-export([is_letter/1, is_upper/1, is_lower/1, is_space/1])."
  puts
  { "is_letter" => "letter", "is_upper" => "upper",
    "is_lower" => "lower", "is_space" => "space" }.each do |fn, name|
    puts "#{fn}(C) -> in_ranges(C, #{name}_ranges())."
  end
  puts
  puts "in_ranges(C, T) -> in_ranges(C, T, 1, tuple_size(T))."
  puts "in_ranges(_C, _T, Low, High) when Low > High -> false;"
  puts "in_ranges(C, T, Low, High) ->"
  puts "    Mid = (Low + High) div 2,"
  puts "    {Start, End} = element(Mid, T),"
  puts "    if"
  puts "        C < Start -> in_ranges(C, T, Low, Mid - 1);"
  puts "        C > End   -> in_ranges(C, T, Mid + 1, High);"
  puts "        true      -> true"
  puts "    end."
  puts
  tables.each do |name, table|
    body = table.map { |s, e| "{#{s},#{e}}" }.join(", ")
    puts "#{name.sub("Ranges", "")}_ranges() -> {#{body}}."
    puts
  end
end

def unicode_version
  # Ruby does not expose the version as a constant; derive it from a
  # codepoint whose assignment we can test, or fall back to "current".
  RbConfig::CONFIG["UNICODE_VERSION"] || "current"
end

case ARGV[0]
when "case-hxx" then emit_case_hxx
when "case-erl" then emit_case_erl
when "category-hxx" then emit_category_hxx
when "category-erl" then emit_category_erl
else
  warn "usage: unicode_gen.rb {case-hxx|case-erl|category-hxx|category-erl}"
  exit 1
end
